spring:
  application:
    name: eureka-consumer-ribbon
  main:
    allow-bean-definition-overriding: true
server:
  port: 2101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka