spring:
  application:
    name: eureka-consumer-ribbon-hystrix
  main:
    allow-bean-definition-overriding: true
server:
  port: 2101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
